# Generated by Django 5.2.13 on 2026-08-06 14:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('designation', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('document_type', models.CharField(blank=True, choices=[('AADHAAR', 'Aadhaar'), ('PASSPORT', 'Passport'), ('PAN', 'PAN Card'), ('DRIVING_LICENSE', 'Driving License'), ('COMPANY_ID', 'Company ID')], max_length=20)),
                ('document_number', models.CharField(blank=True, max_length=60)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='visitor_documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])])),
                ('vehicle_number', models.CharField(blank=True, max_length=30)),
                ('vehicle_type', models.CharField(blank=True, choices=[('CAR', 'Car'), ('BIKE', 'Bike'), ('TRUCK', 'Truck'), ('VAN', 'Van'), ('OTHER', 'Other')], max_length=10)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('special_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expected_arrival', models.TimeField(default='10:00')),
                ('expected_exit', models.TimeField(default='17:00')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out'), ('ARCHIVED', 'Archived'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=300)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='organizations.building')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visits', to=settings.AUTH_USER_MODEL, verbose_name='Host employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='organizations.organization')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visits.visitor')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='QRPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('signature', models.CharField(editable=False, max_length=64)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_pass', to='visits.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('SECURITY_CONCERN', 'Security Concern'), ('FAKE_DOCUMENTS', 'Fake Documents'), ('MISCONDUCT', 'Misconduct'), ('PERMANENT_BAN', 'Permanent Ban')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklists', to='visits.visitor')),
            ],
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['status', 'visit_date'], name='visits_visi_status_308283_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['organization', 'status'], name='visits_visi_organiz_ae0e60_idx'),
        ),
    ]
