-- SecureGate: full PostgreSQL schema
-- Generated by Django 5.2.17 (sqlmigrate for the complete migration plan)
-- Apply via Supabase SQL editor or `python manage.py migrate`.

--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name" CASCADE;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
-- (no-op)
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
--
-- Alter field email on user
--
-- (no-op)
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field last_login on user
--
-- (no-op)
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field username on user
--
-- (no-op)
--
-- Alter field last_name on user
--
-- (no-op)
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Alter field first_name on user
--
-- (no-op)
--
-- Create model User
--
CREATE TABLE "accounts_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "email" varchar(254) NOT NULL UNIQUE, "full_name" varchar(120) NOT NULL, "phone" varchar(20) NOT NULL, "avatar" varchar(100) NULL, "role" varchar(20) NOT NULL, "failed_login_attempts" integer NOT NULL CHECK ("failed_login_attempts" >= 0), "locked_until" timestamp with time zone NULL, "is_email_verified" boolean NOT NULL, "notification_preferences" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL);
CREATE TABLE "accounts_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE INDEX "accounts_user_email_b2644a56_like" ON "accounts_user" ("email" varchar_pattern_ops);
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_group_id_59c0b32f_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_user_id_52b62117_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_groups" ADD CONSTRAINT "accounts_user_groups_group_id_bd11a704_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
--
-- Create model Building
--
CREATE TABLE "organizations_building" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "address" text NOT NULL, "floors" integer NOT NULL CHECK ("floors" >= 0), "entry_gates" integer NOT NULL CHECK ("entry_gates" >= 0), "exit_gates" integer NOT NULL CHECK ("exit_gates" >= 0), "has_reception_desk" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model Department
--
CREATE TABLE "organizations_department" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "code" varchar(20) NOT NULL);
--
-- Create model Organization
--
CREATE TABLE "organizations_organization" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(200) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "logo" varchar(100) NULL, "tagline" varchar(255) NOT NULL, "address" text NOT NULL, "city" varchar(100) NOT NULL, "country" varchar(100) NOT NULL, "timezone" varchar(80) NOT NULL, "working_hours_start" time NOT NULL, "working_hours_end" time NOT NULL, "security_policies" jsonb NOT NULL, "visitor_policies" jsonb NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model AuditLog
--
CREATE TABLE "organizations_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(120) NOT NULL, "entity_type" varchar(80) NOT NULL, "entity_id" varchar(40) NOT NULL, "details" text NOT NULL, "ip_address" inet NULL, "created_at" timestamp with time zone NOT NULL, "user_id" bigint NULL);
--
-- Create model Floor
--
CREATE TABLE "organizations_floor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "level" integer NOT NULL CHECK ("level" >= 0), "building_id" bigint NOT NULL);
--
-- Create model Gate
--
CREATE TABLE "organizations_gate" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "gate_type" varchar(10) NOT NULL, "building_id" bigint NOT NULL);
--
-- Create model Employee
--
CREATE TABLE "organizations_employee" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "employee_id" varchar(50) NOT NULL UNIQUE, "designation" varchar(150) NOT NULL, "office_location" varchar(150) NOT NULL, "joining_date" date NULL, "status" varchar(20) NOT NULL, "building_id" bigint NULL, "department_id" bigint NULL, "user_id" bigint NOT NULL UNIQUE, "organization_id" bigint NOT NULL);
--
-- Add field organization to department
--
ALTER TABLE "organizations_department" ADD COLUMN "organization_id" bigint NOT NULL CONSTRAINT "organizations_depart_organization_id_28713c14_fk_organizat" REFERENCES "organizations_organization"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "organizations_depart_organization_id_28713c14_fk_organizat" IMMEDIATE;
--
-- Add field organization to building
--
ALTER TABLE "organizations_building" ADD COLUMN "organization_id" bigint NOT NULL CONSTRAINT "organizations_buildi_organization_id_72dafa28_fk_organizat" REFERENCES "organizations_organization"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "organizations_buildi_organization_id_72dafa28_fk_organizat" IMMEDIATE;
CREATE INDEX "organizations_organization_slug_e36fd8f9_like" ON "organizations_organization" ("slug" varchar_pattern_ops);
ALTER TABLE "organizations_auditlog" ADD CONSTRAINT "organizations_auditlog_user_id_f504c460_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "organizations_auditlog_user_id_f504c460" ON "organizations_auditlog" ("user_id");
ALTER TABLE "organizations_floor" ADD CONSTRAINT "organizations_floor_building_id_908a2692_fk_organizat" FOREIGN KEY ("building_id") REFERENCES "organizations_building" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "organizations_floor_building_id_908a2692" ON "organizations_floor" ("building_id");
ALTER TABLE "organizations_gate" ADD CONSTRAINT "organizations_gate_building_id_fc1c4159_fk_organizat" FOREIGN KEY ("building_id") REFERENCES "organizations_building" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "organizations_gate_building_id_fc1c4159" ON "organizations_gate" ("building_id");
ALTER TABLE "organizations_employee" ADD CONSTRAINT "organizations_employ_building_id_196f1b37_fk_organizat" FOREIGN KEY ("building_id") REFERENCES "organizations_building" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "organizations_employee" ADD CONSTRAINT "organizations_employ_department_id_c813582b_fk_organizat" FOREIGN KEY ("department_id") REFERENCES "organizations_department" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "organizations_employee" ADD CONSTRAINT "organizations_employee_user_id_4869fb03_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "organizations_employee" ADD CONSTRAINT "organizations_employ_organization_id_b44e87a8_fk_organizat" FOREIGN KEY ("organization_id") REFERENCES "organizations_organization" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "organizations_employee_employee_id_58d5d3fc_like" ON "organizations_employee" ("employee_id" varchar_pattern_ops);
CREATE INDEX "organizations_employee_building_id_196f1b37" ON "organizations_employee" ("building_id");
CREATE INDEX "organizations_employee_department_id_c813582b" ON "organizations_employee" ("department_id");
CREATE INDEX "organizations_employee_organization_id_b44e87a8" ON "organizations_employee" ("organization_id");
CREATE INDEX "organizations_department_organization_id_28713c14" ON "organizations_department" ("organization_id");
CREATE INDEX "organizations_building_organization_id_72dafa28" ON "organizations_building" ("organization_id");
--
-- Add field organization to user
--
ALTER TABLE "accounts_user" ADD COLUMN "organization_id" bigint NULL CONSTRAINT "accounts_user_organization_id_d808f5ca_fk_organizat" REFERENCES "organizations_organization"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "accounts_user_organization_id_d808f5ca_fk_organizat" IMMEDIATE;
--
-- Add field user_permissions to user
--
CREATE TABLE "accounts_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
CREATE INDEX "accounts_user_organization_id_d808f5ca" ON "accounts_user" ("organization_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_user_id_e4f0a161_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "accounts_user_user_permissions" ADD CONSTRAINT "accounts_user_user_p_permission_id_113bb443_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" bigint NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_accounts_user_id" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
--
-- Alter field action_time on logentry
--
-- (no-op)
--
-- Alter field action_flag on logentry
--
-- (no-op)
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
--
-- Create model BlacklistedToken
--
CREATE TABLE "token_blacklist_blacklistedtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "blacklisted_at" timestamp with time zone NOT NULL);
--
-- Create model OutstandingToken
--
CREATE TABLE "token_blacklist_outstandingtoken" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "jti" uuid NOT NULL UNIQUE, "token" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "expires_at" timestamp with time zone NOT NULL, "user_id" bigint NOT NULL);
--
-- Add field token to blacklistedtoken
--
ALTER TABLE "token_blacklist_blacklistedtoken" ADD COLUMN "token_id" integer NOT NULL UNIQUE CONSTRAINT "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" REFERENCES "token_blacklist_outstandingtoken"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "token_blacklist_blac_token_id_3cc7fe56_fk_token_bla" IMMEDIATE;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outs_user_id_83bc629a_fk_accounts_" FOREIGN KEY ("user_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "token_blacklist_outstandingtoken_user_id_83bc629a" ON "token_blacklist_outstandingtoken" ("user_id");
--
-- Add field jti_hex to outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ADD COLUMN "jti_hex" varchar(255) NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Alter field jti_hex on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "jti_hex" SET NOT NULL;
ALTER TABLE "token_blacklist_outstandingtoken" ADD CONSTRAINT "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq" UNIQUE ("jti_hex");
CREATE INDEX "token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like" ON "token_blacklist_outstandingtoken" ("jti_hex" varchar_pattern_ops);
--
-- Remove field jti from outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" DROP COLUMN "jti" CASCADE;
--
-- Rename field jti_hex on outstandingtoken to jti
--
ALTER TABLE "token_blacklist_outstandingtoken" RENAME COLUMN "jti_hex" TO "jti";
--
-- Alter field created_at on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "created_at" DROP NOT NULL;
--
-- Alter field user on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "user_id" DROP NOT NULL;
--
-- Alter field id on blacklistedtoken
--
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
--
-- Alter field id on outstandingtoken
--
ALTER TABLE "token_blacklist_outstandingtoken" ALTER COLUMN "id" TYPE bigint USING "id"::bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ALTER COLUMN "token_id" TYPE bigint USING "token_id"::bigint;
ALTER TABLE "token_blacklist_blacklistedtoken" ADD CONSTRAINT "token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk" FOREIGN KEY ("token_id") REFERENCES "token_blacklist_outstandingtoken" ("id") DEFERRABLE INITIALLY DEFERRED;
--
-- Alter field id on blacklistedtoken
--
-- (no-op)
--
-- Alter field id on outstandingtoken
--
-- (no-op)
--
-- Alter field user on outstandingtoken
--
-- (no-op)
--
-- Change Meta options on blacklistedtoken
--
-- (no-op)
--
-- Change Meta options on outstandingtoken
--
-- (no-op)
--
-- Create model Visitor
--
CREATE TABLE "visits_visitor" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "full_name" varchar(150) NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "company" varchar(150) NOT NULL, "designation" varchar(150) NOT NULL, "address" text NOT NULL, "photo" varchar(100) NULL, "document_type" varchar(20) NOT NULL, "document_number" varchar(60) NOT NULL, "document_file" varchar(100) NULL, "vehicle_number" varchar(30) NOT NULL, "vehicle_type" varchar(10) NOT NULL, "emergency_contact" varchar(100) NOT NULL, "emergency_phone" varchar(20) NOT NULL, "special_notes" text NOT NULL, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model Visit
--
CREATE TABLE "visits_visit" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "visit_id" uuid NOT NULL UNIQUE, "purpose" varchar(200) NOT NULL, "notes" text NOT NULL, "visit_date" date NOT NULL, "expected_arrival" time NOT NULL, "expected_exit" time NOT NULL, "status" varchar(20) NOT NULL, "registered_at" timestamp with time zone NOT NULL, "approved_at" timestamp with time zone NULL, "rejected_at" timestamp with time zone NULL, "rejection_reason" varchar(300) NOT NULL, "checked_in_at" timestamp with time zone NULL, "checked_out_at" timestamp with time zone NULL, "archived_at" timestamp with time zone NULL, "building_id" bigint NULL, "checked_in_by_id" bigint NULL, "checked_out_by_id" bigint NULL, "created_by_id" bigint NULL, "host_id" bigint NULL, "organization_id" bigint NOT NULL, "visitor_id" bigint NOT NULL);
--
-- Create model QRPass
--
CREATE TABLE "visits_qrpass" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "token" uuid NOT NULL UNIQUE, "signature" varchar(64) NOT NULL, "generated_at" timestamp with time zone NOT NULL, "expires_at" timestamp with time zone NOT NULL, "is_used" boolean NOT NULL, "used_at" timestamp with time zone NULL, "visit_id" bigint NOT NULL UNIQUE);
--
-- Create model Blacklist
--
CREATE TABLE "visits_blacklist" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "reason" varchar(30) NOT NULL, "comment" text NOT NULL, "is_active" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "added_by_id" bigint NULL, "visitor_id" bigint NOT NULL);
--
-- Create index visits_visi_status_308283_idx on field(s) status, visit_date of model visit
--
CREATE INDEX "visits_visi_status_308283_idx" ON "visits_visit" ("status", "visit_date");
--
-- Create index visits_visi_organiz_ae0e60_idx on field(s) organization, status of model visit
--
CREATE INDEX "visits_visi_organiz_ae0e60_idx" ON "visits_visit" ("organization_id", "status");
ALTER TABLE "visits_visit" ADD CONSTRAINT "visits_visit_building_id_8fd8f86e_fk_organizations_building_id" FOREIGN KEY ("building_id") REFERENCES "organizations_building" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_visit" ADD CONSTRAINT "visits_visit_checked_in_by_id_958af7ed_fk_accounts_user_id" FOREIGN KEY ("checked_in_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_visit" ADD CONSTRAINT "visits_visit_checked_out_by_id_4e74c952_fk_accounts_user_id" FOREIGN KEY ("checked_out_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_visit" ADD CONSTRAINT "visits_visit_created_by_id_6f9772e6_fk_accounts_user_id" FOREIGN KEY ("created_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_visit" ADD CONSTRAINT "visits_visit_host_id_abbf8e55_fk_accounts_user_id" FOREIGN KEY ("host_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_visit" ADD CONSTRAINT "visits_visit_organization_id_d71a5677_fk_organizat" FOREIGN KEY ("organization_id") REFERENCES "organizations_organization" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_visit" ADD CONSTRAINT "visits_visit_visitor_id_de3c9f1e_fk_visits_visitor_id" FOREIGN KEY ("visitor_id") REFERENCES "visits_visitor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "visits_visit_building_id_8fd8f86e" ON "visits_visit" ("building_id");
CREATE INDEX "visits_visit_checked_in_by_id_958af7ed" ON "visits_visit" ("checked_in_by_id");
CREATE INDEX "visits_visit_checked_out_by_id_4e74c952" ON "visits_visit" ("checked_out_by_id");
CREATE INDEX "visits_visit_created_by_id_6f9772e6" ON "visits_visit" ("created_by_id");
CREATE INDEX "visits_visit_host_id_abbf8e55" ON "visits_visit" ("host_id");
CREATE INDEX "visits_visit_organization_id_d71a5677" ON "visits_visit" ("organization_id");
CREATE INDEX "visits_visit_visitor_id_de3c9f1e" ON "visits_visit" ("visitor_id");
ALTER TABLE "visits_qrpass" ADD CONSTRAINT "visits_qrpass_visit_id_9d6872d1_fk_visits_visit_id" FOREIGN KEY ("visit_id") REFERENCES "visits_visit" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_blacklist" ADD CONSTRAINT "visits_blacklist_added_by_id_a2edc1ae_fk_accounts_user_id" FOREIGN KEY ("added_by_id") REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "visits_blacklist" ADD CONSTRAINT "visits_blacklist_visitor_id_23aa61dd_fk_visits_visitor_id" FOREIGN KEY ("visitor_id") REFERENCES "visits_visitor" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "visits_blacklist_added_by_id_a2edc1ae" ON "visits_blacklist" ("added_by_id");
CREATE INDEX "visits_blacklist_visitor_id_23aa61dd" ON "visits_blacklist" ("visitor_id");-- Mark all migrations as applied so Django's migrate is a no-op after bootstrap.
INSERT INTO django_migrations (app, name, applied) VALUES

    ('contenttypes', '0001_initial', now()),
    ('contenttypes', '0002_remove_content_type_name', now()),
    ('auth', '0001_initial', now()),
    ('auth', '0002_alter_permission_name_max_length', now()),
    ('auth', '0003_alter_user_email_max_length', now()),
    ('auth', '0004_alter_user_username_opts', now()),
    ('auth', '0005_alter_user_last_login_null', now()),
    ('auth', '0006_require_contenttypes_0002', now()),
    ('auth', '0007_alter_validators_add_error_messages', now()),
    ('auth', '0008_alter_user_username_max_length', now()),
    ('auth', '0009_alter_user_last_name_max_length', now()),
    ('auth', '0010_alter_group_name_max_length', now()),
    ('auth', '0011_update_proxy_permissions', now()),
    ('auth', '0012_alter_user_first_name_max_length', now()),
    ('accounts', '0001_initial', now()),
    ('organizations', '0001_initial', now()),
    ('accounts', '0002_initial', now()),
    ('admin', '0001_initial', now()),
    ('admin', '0002_logentry_remove_auto_add', now()),
    ('admin', '0003_logentry_add_action_flag_choices', now()),
    ('sessions', '0001_initial', now()),
    ('token_blacklist', '0001_initial', now()),
    ('token_blacklist', '0002_outstandingtoken_jti_hex', now()),
    ('token_blacklist', '0003_auto_20171017_2007', now()),
    ('token_blacklist', '0004_auto_20171017_2013', now()),
    ('token_blacklist', '0005_remove_outstandingtoken_jti', now()),
    ('token_blacklist', '0006_auto_20171017_2113', now()),
    ('token_blacklist', '0007_auto_20171017_2214', now()),
    ('token_blacklist', '0008_migrate_to_bigautofield', now()),
    ('token_blacklist', '0010_fix_migrate_to_bigautofield', now()),
    ('token_blacklist', '0011_linearizes_history', now()),
    ('token_blacklist', '0012_alter_outstandingtoken_user', now()),
    ('token_blacklist', '0013_alter_blacklistedtoken_options_and_more', now()),
    ('visits', '0001_initial', now())
 ON CONFLICT DO NOTHING;
